/**/*:
  ros__parameters:

    dataset: nuscenes
    dataset_split: mini_val  # train, val, test, mini_train, mini_val

    publish_ego_data: true
    publish_camera_images: true
    publish_lidar_pointclouds: true
    publish_lidar_object_lists: true
    publish_camera_01_object_lists: false
