/**/*:
  ros__parameters:

    dataset: driving
    dataset_split: dusk  # all, day, dusk, night
    driving_auto_download: true
    driving_download_workers: 8  # concurrent archive downloads (1-32)
    driving_rosbag_duration_seconds: 20.0

    publish_ego_data: true
    publish_camera_images: true
    publish_lidar_pointclouds: true
    publish_lidar_object_lists: true
