/**/*:
  ros__parameters:

    ## Common Parameters ##
    use_camera: true
    use_lidar: true
    use_radar: true

    ## Waymo Open Dataset ##
    dataset: waymo_open_dataset
    dataset_split: validation_mini  # validation, training, validation_mini, training_mini
    object_model: HEXAMOTION  # HEXAMOTION, CAMERA2D
    waymo_min_lidar_points_in_bbox: 1
    waymo_lidar_object_list_filter_cam_front: false
