/**/*:
  ros__parameters:

    ## Common Parameters ##
    use_camera: true
    use_lidar: true
    use_radar: false  # not implemented yet

    ## NuScenes ##
    dataset: nuscenes
    dataset_split: mini_val  # train, val, test, mini_train, mini_val
