name: docker-ros

# TODO: what is the best setup for PR workflows? see https://github.com/ika-rwth-aachen/etsi_its_messages/blob/main/.github/workflows/docker-ros.yml?
# TODO: to enable GHCR
# - Org Settings / Actions / Workflow permissions / Read and write permissions
on:
  push:
  workflow_dispatch:

jobs:
  latest:
    runs-on: ubuntu-latest
    steps:
      - uses: ika-rwth-aachen/docker-ros@main
        with:
          platform: amd64
          target: dev,run
          base-image: rwthika/ros2:latest
          command: ros2 run ros2_demo_package ros2_demo_node
          enable-slim: false
